server:
  port: 9022
  servlet:
    context-path:

spring:
  application:
    name: mall-supplier

  # Redis配置
  redis:
    host: 192.168.1.201
    port: 16379
    password: 123456
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

  # json转换配置
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # Spring Boot Admin监控组件的Server地址
  boot:
    admin:
      client:
        url: http://localhost:9001
        username: admin
        password: admin123

# 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


# Swagger配置
swagger:
  title: mall-site 供应商服务系统接口文档
  version: 2021.0
  description: 本文档涵盖了供应商端所有API的说明文档以及在线调试服务。
  exclude-path: /error # 排除的api
  base-package: com.wzliulan.mall
  contact:
    name: 梧州浏览科技
    url: www.wzliulan.com
    email: wzliulan@qq.com
  authorization:
    key-name: token

